// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentWalletTransaction = { id: string, wallet_id: string, direction: string, amount: number, description: string, metadata: string | null, task_id: string | null, process_id: string | null, created_at: Date, };
