// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentWallet = { id: string, profile_key: string, display_name: string, budget_limit: number, spent_amount: number, created_at: Date, updated_at: Date, };
