// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DependencyType } from "./DependencyType";

export type CreateTaskDependency = { project_id: string, source_task_id: string, target_task_id: string, dependency_type: DependencyType, };
