// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateTimeEntry = { project_id: string, task_id: string, description: string | null, start_time: string, end_time: string | null, duration_seconds: bigint | null, };
