// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectBoardType } from "./ProjectBoardType";

export type CreateProjectBoard = { project_id: string, name: string, slug: string, board_type: ProjectBoardType, description: string | null, metadata: string | null, };
