// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomFieldType } from "./CustomFieldType";

export type CustomFieldDefinition = { id: string, project_id: string, name: string, field_type: CustomFieldType, required: boolean, options?: Record<string, unknown> | null, default_value?: unknown, metadata?: Record<string, unknown> | null, created_at: string, updated_at: string, };
