// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomFieldType } from "./CustomFieldType";

export type UpdateCustomFieldDefinition = { name: string | null, field_type: CustomFieldType | null, required: boolean | null, options: Record<string, unknown> | null, default_value: unknown, metadata: Record<string, unknown> | null, };
