// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectBoardType } from "./ProjectBoardType";

export type UpdateProjectBoard = { name: string | null, slug: string | null, board_type: ProjectBoardType | null, description: string | null | null, metadata: string | null | null, };
